config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#index'
  get 'shop' => 'pages#shop'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

	validates :title, :description, presence: true
	validates :price, numericality: {greater_than_or_equal_to: 0.01}
	validates :title, uniqueness: true

	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	  	@products = Product.all
  end

  def shop
  	@products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Store</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'http://fonts.googleapis.com/css?family=Raleway:400,700,600,500,300'%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%= render 'shared/header'%>

		<div class="main-container">
			 <%= yield %>
			<%= render 'shared/footer'%>
		</div><!-- /.main-container -->
   
  </body>
</html>

app/views/pages/index.html.erb
<header class="fullscreen-element">
				<div class="background-image-holder parallax-background overlay" data-stellar-background-ratio="0.9">
					<%= image_tag('bg-top.jpg', class: 'background-image', alt:'Background') %>
				</div>

				<div class="container align-vertical hero">
					<div class="row">
						<div class="col-md-5 col-sm-5 col-md-offset-7 col-sm-offset-7 text-left">
							<h1>Viziit</h1>
							<p>Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates depudiandae sint et molestiae.</p>
							<div class="button-group">
								<%= link_to 'Shop Now', root_path, class: 'btn btn-primary' %>
							</div>
						</div>
					</div><!--end of row-->
				</div><!--end of container-->
			</header>

			<div class="action-bar">
				<div class="container">
					<div class="row">
						<div class="col-sm-4">
							<a href="#"><span data-icon="v" class="icon"></span> <span class="text">Fast Delivery</span></a>
						</div>
						<div class="col-sm-4">
							<a href="#"><span data-icon="/" class="icon"></span> <span class="text">Adjustable</span></a>
						</div>
						<div class="col-sm-4">
							<a href="#"><span data-icon="7" class="icon"></span> <span class="text">Inovative</span></a>
						</div>
					</div><!-- /.row -->
				</div><!-- /.container -->
			</div>

			<section>
				<div class="background-image-holder overlay" data-stellar-background-ratio="0.9">
					<%= image_tag('bg-top.jpg', class: 'background-image', alt:'Background')%>
				</div>
				<div class="container">
					<div class="row">
						<div class="col-sm-5 text-left">
							<h2 class="page-title">For your familly</h2>
							<p class="description">Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates depudiandae sint et molestiae.</p>
							<a href="#" class="btn btn-primary">Shop Now</a>
						</div>
					</div><!--end of row-->
				</div><!--end of container-->
			</section>
			<br>

			<h2 class="page-title text-center"></h2>
			<%= render 'shared/list' %>

			<section>
				<div class="background-image-holder on-page overlay">
					<%= image_tag('bg-top.jpg', class: 'background-image', alt:'Background') %>
				</div>
				<div class="container">
					<div class="row">
						<div class="col-sm-5 col-sm-offset-7 text-right">
							<h2 class="page-title">Modern Chair<span class="accent-color">.</span></h2>
							<p class="description">Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates depudiandae sint et molestiae.</p>
							<%= link_to 'Shop Now', root_path, class: 'btn btn-primary'%>
						</div>
					</div><!--end of row-->
				</div><!--end of container-->
			</section>

app/views/pages/shop.html.erb
<header class="secondary">
	<div class="background-image-holder parallax-background overlay" data-stellar-background-ratio="0.9">
		<%= image_tag('bg-top.jpg', class: 'background-image', alt:'Background')%>
	</div>

	<div class="container align-vertical hero">
		<div class="row">
			<div class="col-md-5 text-left">
				<h1>Our Shop</h1>
				<p>Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates depudiandae sint et molestiae.</p>
			</div>
		</div><!--end of row-->
	</div><!--end of container-->
</header>

<section class="product-list">
	<div class="container">
		<% @products.each do |product| %>
		<div class="row">
			<div class="col-md-12">
				<div class="product">
					<div class="row">
						<div class="col-md-6 col-xs-12">
							<div class="thumbnail">
								<%= image_tag product.image %>
								
							</div>
						</div>
						<div class="col-md-5 col-md-offset-1">
							<div class="product-details">
								<h2 class="product-title">
									<%= product.title%>
								</h2>
								<p class="product-price">
									<%= number_to_currency product.price %>
								</p>
								<p>
									<%= product.description %>
								</p>

								<a href="#" class="btn btn-default"><i class="fa fa-shopping-cart"></i> Add to cart</a>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div><!-- /.row -->
		<% end %>
	</div>
</section>

<div class="no-padding-top section">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<a href="#" class="load-more"><i class="fa fa-ellipsis-h"></i></a>
			</div>
		</div><!-- /.row -->
	</div><!-- /.container -->
</div>

app/views/shared/_footer.html.erb
			<section class="newsletter accent-bg">
				<div class="background-image-holder overlay accent" data-stellar-background-ratio="0.9">
					<%= image_tag('bg-top.jpg', class: 'background-image', alt:'Background') %>
				</div>
				<div class="container">
					<div class="row">
						<div class="col-md-5 text-left">
							<h2 class="page-title">Join our newsletter</h2>
							<p>Bemporibus autem quibusdam et aut officiis debitis autem quibusdam et aut officiis debitis.</p>
						</div>
						<div class="col-md-4">
							<form class="newsletter-form">
								<input type="text" name="email" id="email" placeholder="Your email address">
							</form>
						</div>
						<div class="col-md-3">
							<%= link_to 'Join Now', root_path, class: 'btn btn-primary'%>
						</div>
					</div><!--end of row-->
				</div><!--end of container-->
			</section>

			<footer class="footer">
				<div class="container">
					<div class="row">
						<div class="col-md-6 col-md-offset-3">
							<ul class="footer-navigation">
								<li class="active">
									<%= link_to 'Home', root_path %>
								</li>
								<li>
									<%= link_to 'Store', shop_path %>
								</li>
								<li>
									<%= link_to 'About', root_path %>
								</li>
								<li>
									<%= link_to root_path do %>
										<i class="fa fa-paper-plane"></i>Contact
									<% end %>
								</li>
								<li><a href="./contact.html"><i class="fa fa-paper-plane"></i> Contact</a></li>
							</ul>
							<ul class="accepted-payments">
								<li>
									<%= link_to root_path do %>
										<i class="fa fa-cc-amex"></i>
									<% end %>
								</li>
								<li>
									<%= link_to root_path do %>
										<i class="fa fa-cc-visa"></i>
									<% end %>
								</li>
								<li>
									<%= link_to root_path do %>
										<i class="fa fa-cc-paypal"></i>
									<% end %>
								</li>
								<li>
									<%= link_to root_path do %>
										<i class="fa fa-cc-stripe"></i>
									<% end %>
								</li>
								<li>
									<%= link_to root_path do %>
										<i class="fa fa-cc-mastercard"></i>
									<% end %>
								</li>
							</ul>
							<div class="copyright">
								<p>Copyright © 2016 Viziit. Created by Ainor Technologies</p>
							</div>
						</div>
					</div><!-- /.row -->
				</div><!-- /.container -->
			</footer>

app/views/shared/_header.html.erb
  <div id="sidr">
			<ul>
				<li>
				<%= link_to '#', class: "side-logo" do %>
					My Store <span class="logo-dot accent-bg"></span>
				<% end %>
				</li>
				<li class="active">
				<%= link_to 'Store', shop_path %>
				</li>	
				<li class="divider"><span></span></li>
				<li>
					<%= link_to 'Privacy', root_path %>
				</li>
				<li>
					<%= link_to 'Terms  & Conditions', root_path %>
				</li>
			</ul>
			<div class="side-social">
				<a href="#"><i class="fa fa-facebook"></i></a>
				<a href="#"><i class="fa fa-twitter"></i></a>
				<a href="#"><i class="fa fa-google-plus"></i></a>
				<a href="#"><i class="fa fa-pinterest"></i></a>
				<a href="#"><i class="fa fa-instagram"></i></a>
			</div>
		</div>

		<div class="nav-container">
			<nav class="navbar navbar-default">
				<div class="container">
					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="navbar-header">
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapse-navigation" aria-expanded="false">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						</button>
						<%= link_to root_path, class: 'navbar-brand' do %>
							Viziit<span class="logo-dot accent-bg"></span>
						<% end %>
						<a href="#sidr" class="side-menu-opener mobile">
							<div class="bars">
						        <span class="bar top"></span>
						        <span class="bar middle"></span>
						        <span class="bar bottom"></span>
						    </div>
						</a>
					</div>

					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse" id="collapse-navigation">
						<ul class="nav navbar-nav">
							<li>
								<%= link_to 'Home', root_path %>
							</li>
							<li>
								<%= link_to 'Store', shop_path %>
							</li>
							<li>
								<%= link_to 'About', root_path %>
							</li>
							<li>
								<%= link_to root_path do %>
								 <i class="fa fa-paper-plane"></i> Contact
								<% end %>
							</li>
							<li>
								<%= link_to root_path, class: 'menu-cart' do %>
									<i class="fa fa-shopping-cart"></i> RM 0.00
								<% end %>
							</li>
						</ul>
						<ul class="nav navbar-nav navbar-right">
							<li>
								<a href="#sidr" class="side-menu-opener">
									<div class="bars">
								        <span class="bar top"></span>
								        <span class="bar middle"></span>
								        <span class="bar bottom"></span>
								    </div>
								</a>
							</li>
						</ul>
					</div><!-- /.navbar-collapse -->
				</div><!-- /.container -->
			</nav>
		</div>

app/views/shared/_list.html.erb
<section class="products-grid">
				<div class="container">
					<div class="row products-container">
						<% @products.each do |product| %>
						<% if product.id <= 3 %>
						<div class="col-md-4 col-sm-6 col-xs-12 product">
							<div class="thumbnail" style="background-image: url('image_tag product.name');">
								<div class="product-details text-center">
									<div class="align-vertical">
										<h3><%= product.title %></h3>
										<%= link_to root_path, class: 'btn btn-primary' do %>
										<i class="fa fa-shopping-cart"></i> Add to cart
										<% end %>
										<p class="product-price"><%= number_to_currency product.price %></p>
									</div>
								</div>
							</div>
						</div>
						<% end %>
						<% end %>
					</div><!-- /.row -->
				</div><!-- /.container -->
			</section>